version: "3.7"

services:

  web:
    build: ./
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
    container_name: otrs
    restart: always
    ports:
      - 8083:8083
      - 8082:8082
      - 80:80
      - 443:443
      - 1901:1901
    volumes:
      - ./httpd/html/:/usr/local/apache2/htdocs/
      - ./cert/server.crt:/usr/local/apache2/conf/server.crt
      - ./cert/server.key:/usr/local/apache2/conf/server.key
      - ./httpd/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd/conf/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
      - apache2:/usr/local/apache2
      - otrs:/opt/
    networks: 
      - otrs
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_USER: otrs
      MARIADB_PASSWORD: jurema
      MARIADB_DATABASE: otrs
      MARIADB_ROOT_PASSWORD: jurema
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./db/conf/50-znuny_config.cnf:/etc/mysql/mariadb.conf.d/50-znuny_config.cnf
    networks: 
      - otrs
    #depends_on:
    #  - web
networks:
  otrs:
    driver: bridge
volumes:
  mysql:
  apache2:
  otrs: