version: "3.7"

services:

  web:
    build: ./
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    image: apache
    container_name: otrs
    restart: always
    ports:
      - 8083:8083
      - 8082:8082
      - 80:80
      - 443:443
      - 1901:1901
    volumes:
      - ./web/html/:/usr/local/apache2/htdocs/
      - apache2:/usr/local/apache2
    networks: 
      - otrs
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_USER: otrs
      MARIADB_PASSWORD: jurema
      MARIADB_DATABASE: otrs
      MARIADB_ROOT_PASSWORD: jurema
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./db/conf/zotrs.cnf:/etc/mysql/mariadb.conf.d/zotrs.cnf
      - ./db/conf/utf8.cnf:/etc/mysql/mariadb.conf.d/utf8.cnf
    networks: 
      - otrs
    #depends_on:
    #  - web
networks:
  otrs:
    driver: bridge

volumes:
  mysql:
  apache2:
